### ISSUE TITLE
How do I use this software for analysis and conversion exactly? 

### ISSUE THREAD

**Issue by RajSakpal** [proleap/proleap-vb6#1]
For Cobol - Java conversion we had to open [ProLeapCobolEmbeddedJetty](https://github.com/proleap/proleap-cobol/blob/main/proleap-cobol-app/src/main/java/io/proleap/cobol/ProLeapCobolEmbeddedJetty.java) and run the main method as java application.

Is there a similar process for this.

**Comment by uwol** [comment]
Hi @RajSakpal , there is no such server for Visual Basic. So one would have to implement such as server, if such a transformation pipeline should be executed on the Web. Beste, Ulrich
